PRAGMA foreign_keys=ON;
BEGIN TRANSACTION;
CREATE TABLE [Plant](
  [ID] INTEGER PRIMARY KEY AUTOINCREMENT,
  [NAME] VARCHAR(100) NOT NULL UNIQUE,
  [HIERARCHY] INTEGER NOT NULL);

CREATE TABLE [Image](
  [ID] INTEGER PRIMARY KEY AUTOINCREMENT,
  [IMAGEBIN] BLOB,
  [IMAGEFORMAT] VARCHAR(255),
  [PLANTID] INT UNIQUE REFERENCES [Plant]([ID]) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE [NumberTag](
  [ID] INTEGER PRIMARY KEY AUTOINCREMENT,
  [KEY] VARCHAR(255) NOT NULL,
  [VALUE] FLOAT NOT NULL,
  [PLANTID] INTEGER REFERENCES [Plant]([ID]) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE [ProjectDir](
  [ID] INT PRIMARY KEY,
  [DIR] VARCHAR(255));

CREATE TABLE [StringTag](
  [ID] INTEGER PRIMARY KEY AUTOINCREMENT,
  [KEY] VARCHAR(255) NOT NULL,
  [VALUE] VARCHAR(255) NOT NULL,
  [PLANTID] INTEGER REFERENCES [Plant]([ID]) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE INDEX [FINDBYHIERARCHY] ON [Plant]([HIERARCHY]);

CREATE INDEX [FINDBYNAME] ON [Plant]([NAME]);

CREATE INDEX [FINDNUMTAG]
ON [NumberTag](
  [KEY],
  [VALUE]);

CREATE INDEX [FINDSTRTAG]
ON [StringTag](
  [KEY],
  [VALUE]);

COMMIT;
